' src/themes/ontario-health/_colors.puml

!$OH_THEME_ENABLED ?= %false()


'Set OH Colours

!$OH_COLOR_PRIMARY ?= "#D6EAF8"
!$OH_COLOR_PRIMARY_LIGHT ?= "#D6EAF8"
!$OH_COLOR_PRIMARY_DARK ?= "#D6EAF8"

!$OH_COLOR_WARNING ?= "#FCF3CF"
!$OH_COLOR_WARNING_LIGHT ?= "#FCF3CF"
!$OH_COLOR_WARNING_DARK ?= "#FCF3CF"

!$OH_COLOR_SUCCESS ?= "#D5F5E3"
!$OH_COLOR_SUCCESS_LIGHT ?= "#D5F5E3"
!$OH_COLOR_SUCCESS_DARK ?= "#D5F5E3"

!$OH_COLOR_ERROR ?= "Red"
!$OH_COLOR_ERROR_LIGHT ?= "Red"
!$OH_COLOR_ERROR_DARK ?= "Red"

!$OH_COLOR_TEXT ?= "#000000"
!$OH_COLOR_BORDER ?= "#5D6D7E"


'Set OH Colours to TOGAF
!$OH_COLOR_BUSINESS ?= $OH_COLOR_WARNING
!$OH_COLOR_LOGICAL ?= $OH_COLOR_PRIMARY
!$OH_COLOR_DEPLOYMENT ?= "#FAD7A0"
!$OH_COLOR_TECHNOLOGY ?= $OH_COLOR_SUCCESS
!$OH_COLOR_EXTERNAL ?= "#E8DAEF"
