' src/themes/ontario-health/_colors.puml


'Set OH Colours

!$COLOR_OH_LABEL ?= "#4D4D4D"
!$COLOR_OH_PLACEHOLDER ?= "#737373"
!$COLOR_OH_DISABLED_MILD ?= "#737373"
!$COLOR_OH_DISABLED_MILD ?= "#4D4D4D"

'$COLOR_OH_BRAND_HOVER ?= "#049A5"

'FOCUS_COLOR ?= "#F2FBFF"
'ACCENT_COLOR ?= "#00B2E3" 
'BRIGHT BLUE


!$COLOR_OH_PRIMARY ?= "#047BC1"
!$COLOR_OH_PRIMARY_LIGHT ?= "#D6EAF8"
!$COLOR_OH_PRIMARY_DARK ?= "#023451"

!$COLOR_OH_WARNING ?= "#FCAF17"
!$COLOR_OH_WARNING_LIGHT ?= "#EFB243"
!$COLOR_OH_WARNING_DARK ?= "#FFFAEB"
'FFFAEB

!$COLOR_OH_SUCCESS ?= "#118847"
!$COLOR_OH_SUCCESS_LIGHT ?= "#EAF5EA"
!$COLOR_OH_SUCCESS_DARK ?= "#0F7C41"

!$COLOR_OH_ERROR ?= "#CD0000"
!$COLOR_OH_ERROR_LIGHT ?= "#FCEFF0"
!$COLOR_OH_ERROR_DARK ?= "#8a0101"

'! $COLOR_OH_EMPHASIS ?= "#9333EA"
'! $COLOR_OH_EMPHASIS_LIGHT ?= "#"
'! $COLOR_OH_EMPHASIS_DARK ?= "#"

!$COLOR_OH_TEXT ?= "#1A1A1A"
!$COLOR_OH_BORDER ?= "#5D6D7E"


'Set OH Colours to TOGAF
!$COLOR_OH_BUSINESS ?= $COLOR_OH_WARNING
!$COLOR_OH_LOGICAL ?= $COLOR_OH_PRIMARY
!$COLOR_OH_DEPLOYMENT ?= "#FAD7A0"
!$COLOR_OH_TECHNOLOGY ?= $COLOR_OH_SUCCESS
!$COLOR_OH_EXTERNAL ?= "#E8DAEF"


!$COLOR_OH_MOTIVATION_LIGHT ?= "#F1E3F2"
!$COLOR_OH_MOTIVATION_DARK ?= "#B975B7"
!$COLOR_OH_STRATEGY_LIGHT ?= "#F8E5C3"
!$COLOR_OH_STRATEGY_DARK ?= "#EFB243"
!$COLOR_OH_BUSINESS_LIGHT ?= "#FFFDC4"
!$COLOR_OH_BUSINESS_DARK ?= "#FFD440"
!$COLOR_OH_APPLICATION_LIGHT ?= "#C5EEFA"
!$COLOR_OH_APPLICATION_DARK ?= "#3193CC"
!$COLOR_OH_TECHNOLOGY_LIGHT ?= "#D1EFD4"
!$COLOR_OH_TECHNOLOGY_DARK ?= "#39B54A"
!$COLOR_OH_IMPLEMENTATION_LIGHT ?= "#FEE1D9"
!$COLOR_OH_IMPLEMENTATION_DARK ?= "#F15A22"
!$COLOR_OH_HIGHLIGHTED_LIGHT ?= "#CFEDED"
!$COLOR_OH_HIGHLIGHTED_DARK ?= "#0050EF"
!$COLOR_OH_NEW_LIGHT ?= "#DDEDC7"
!$COLOR_OH_NEW_DARK ?= "#005700"

