' src/themes/ontario-health/_colors.puml


'Set OH Colours

!$OH_COLOR_LABEL ?= "#4D4D4D"
!$OH_COLOR_PLACEHOLDER ?= "#737373"
!$OH_COLOR_DISABLED_MILD ?= "#737373"
!$OH_COLOR_DISABLED_MILD ?= "#4D4D4D"

'$OH_COLOR_BRAND_HOVER ?= "#049A5"

'FOCUS_COLOR ?= "#F2FBFF"
'ACCENT_COLOR ?= "#00B2E3" 
'BRIGHT BLUE


!$OH_COLOR_PRIMARY ?= "#047BC1"
!$OH_COLOR_PRIMARY_LIGHT ?= "#D6EAF8"
!$OH_COLOR_PRIMARY_DARK ?= "#023451"

!$OH_COLOR_WARNING ?= "#FCAF17"
!$OH_COLOR_WARNING_LIGHT ?= "#EFB243"
!$OH_COLOR_WARNING_DARK ?= "#FFFAEB"
'FFFAEB

!$OH_COLOR_SUCCESS ?= "#118847"
!$OH_COLOR_SUCCESS_LIGHT ?= "#EAF5EA"
!$OH_COLOR_SUCCESS_DARK ?= "#0F7C41"

!$OH_COLOR_ERROR ?= "#CD0000"
!$OH_COLOR_ERROR_LIGHT ?= "#FCEFF0"
!$OH_COLOR_ERROR_DARK ?= "#8a0101"

'! $OH_COLOR_EMPHASIS ?= "#9333EA"
'! $OH_COLOR_EMPHASIS_LIGHT ?= "#"
'! $OH_COLOR_EMPHASIS_DARK ?= "#"

!$OH_COLOR_TEXT ?= "#1A1A1A"
!$OH_COLOR_BORDER ?= "#5D6D7E"


'Set OH Colours to TOGAF
!$OH_COLOR_BUSINESS ?= $OH_COLOR_WARNING
!$OH_COLOR_LOGICAL ?= $OH_COLOR_PRIMARY
!$OH_COLOR_DEPLOYMENT ?= "#FAD7A0"
!$OH_COLOR_TECHNOLOGY ?= $OH_COLOR_SUCCESS
!$OH_COLOR_EXTERNAL ?= "#E8DAEF"


!$OH_COLOR_MOTIVATION_LIGHT ?= "#F1E3F2"
!$OH_COLOR_MOTIVATION_DARK ?= "#B975B7"
!$OH_COLOR_STRATEGY_LIGHT ?= "#F8E5C3"
!$OH_COLOR_STRATEGY_DARK ?= "#EFB243"
!$OH_COLOR_BUSINESS_LIGHT ?= "#FFFDC4"
!$OH_COLOR_BUSINESS_DARK ?= "#FFD440"
!$OH_COLOR_APPLICATION_LIGHT ?= "#C5EEFA"
!$OH_COLOR_APPLICATION_DARK ?= "#3193CC"
!$OH_COLOR_TECHNOLOGY_LIGHT ?= "#D1EFD4"
!$OH_COLOR_TECHNOLOGY_DARK ?= "#39B54A"
!$OH_COLOR_IMPLEMENTATION_LIGHT ?= "#FEE1D9"
!$OH_COLOR_IMPLEMENTATION_DARK ?= "#F15A22"
!$OH_COLOR_HIGHLIGHTED_LIGHT ?= "#CFEDED"
!$OH_COLOR_HIGHLIGHTED_DARK ?= "#0050EF"
!$OH_COLOR_NEW_LIGHT ?= "#DDEDC7"
!$OH_COLOR_NEW_DARK ?= "#005700"

