

'! $COLOR_FONT_TITLE = $COLOR_OH_PRIMARY_DARK
'! $COLOR_LINE_TITLE = $COLOR_OH_PRIMARY

!$ROUND_CORNER_TITLE = 0

!$BACKGROUND_TITLE = "PRIMARY_DARK"
!$COLOR_FONT_TITLE = "AUTO"
    
!$COLOR_LINE_TITLE = "CURRENT" 
