'---------------------------------------------------------
' Title Constants
'---------------------------------------------------------

!$MARGIN_OH_TITLE ?= 20
!$PADDING_OH_TITLE ?= 15
!$ROUND_OH_CORNER_TITLE ?= 0


!$COLOR_OH_BACKGROUND_TITLE ?= "PRIMARY_DARK"
!$COLOR_OH_FONT_TITLE ?= "AUTO"
    
!$COLOR_OH_LINE_TITLE ?= "CURRENT" 
