' src/libraries/togaf/_functions.puml

'---------------------------------------------------------
' Helper Functions for TOGAF library integration
'---------------------------------------------------------

'!function $togaf_layer_name($tg_name)
'  !if ($tg_name == "technology")
'
'  !return $first + " " + $last
'!endfunction

!function $togaf_layer_color($state)
  !if ($state == "success")
    !return "Green"
  !else
    !return "Red"
  !endif
!endfunction

' %get_variable_value
' %set_variable_value
' %upper

' %invoke_procedure($wrapper)
' %call_user_func

' %boolval

' !unquoted procedure 
' !unquoted function  