' src/themes/togaf/_colors.puml

!$TOGAF_THEME_ENABLED ?= %true()

!if ($TOGAF_THEME_ENABLED)

'Use Default TOGAF Colours
!$COLOR_BUSINESS ?= $COLOR_WARNING
!$COLOR_LOGICAL ?= $COLOR_PRIMARY
!$COLOR_DEPLOYMENT ?= "#FAD7A0"
!$COLOR_TECHNOLOGY ?= $COLOR_SUCCESS
!$COLOR_EXTERNAL ?= "#E8DAEF"


' Functional Capabilities = #FCF3CF (light yellow)
' Logical Components / Services = #D6EAF8 (light blue)
' External Systems = #E8DAEF (light purple)
' Deployment Components = #FAD7A0 (light orange)
' Technology Products / Platforms = #D5F5E3 (light green)

!endif