' ========================================================
' Combined PlantUML Library Bundle (SASS-Style Compilation)
' Generated on: 2026-09-11 16:15:26 EDT
' Build Commit Hash: 24afd6f6861a37d7f79b1d535c193ba86e52a40b
' Build Commit Comment: fixed Load_Lib_Styles_Stdlib
' ========================================================

' src/all.puml
' Module Entry Point: OH + TOGAF Component Pack

' --- Importing: src/index.puml ---

' --- Importing: src/libs/index.puml ---
' src/index.puml
' Module Entry Point: OH + TOGAF Component Pack


'STEP 1 :: VARS includes
' --- Importing: src/libs/stdlib/vars/index.puml ---
' src/themes/stdlib/index.puml
' Module Entry Point: Common Theme Variables

' --- Importing: src/libs/stdlib/vars/_colors.puml ---

'---------------------------------------------------------
' Color Constants
'
' !$variable_name ?= "variable_value"
'---------------------------------------------------------

!$COLOR_TRANSPARENT = "#FFFFFF00"
!$COLOR_NONE ?= $COLOR_TRANSPARENT

!$COLOR_PRIMARY ?= "#D6EAF8"
!$COLOR_PRIMARY_LIGHT ?= "#D6EAF8"
!$COLOR_PRIMARY_DARK ?= "#D6EAF8"

!$COLOR_WARNING ?= "#FCF3CF"
!$COLOR_WARNING_LIGHT ?= "#FCF3CF"
!$COLOR_WARNING_DARK ?= "#FCF3CF"

!$COLOR_SUCCESS ?= "#D5F5E3"
!$COLOR_SUCCESS_LIGHT ?= "#D5F5E3"
!$COLOR_SUCCESS_DARK ?= "#D5F5E3"

!$COLOR_ERROR ?= "Red"
!$COLOR_ERROR_LIGHT ?= "Red"
!$COLOR_ERROR_DARK ?= "Red"

!$COLOR_TEXT ?= "#000000"
!$COLOR_TEXT_BACKGROUND ?= "#ffffff"
!$COLOR_BORDER ?= "#5D6D7E"
' --- End Import: src/libs/stdlib/vars/_colors.puml ---

' --- Importing: src/libs/stdlib/vars/_fonts.puml ---

'---------------------------------------------------------
' Font Constants
'
' !$variable_name ?= "variable_value"
'---------------------------------------------------------

!$FONT_NAME ?= "Segoe UI"
!$FONT_SIZE ?= 12
!$FONT_SIZE_TITLE ?= 18
!$FONT_SIZE_LEGEND ?= 11
!$FONT_SIZE_ARROW ?= 11

!$FONT_COLOR ?= $COLOR_TEXT
' --- End Import: src/libs/stdlib/vars/_fonts.puml ---


' --- Importing: src/libs/stdlib/vars/_borders.puml ---

'---------------------------------------------------------
' Border Constants
'
' !$variable_name ?= "variable_value"
'---------------------------------------------------------

!$BORDER_THICKNESS ?= 1
!$BORDER_THICKNESS_BOLD ?= 2
!$BORDER_THICKNESS_POD ?= 2
' --- End Import: src/libs/stdlib/vars/_borders.puml ---


' --- Importing: src/libs/stdlib/vars/_layout.puml ---

'---------------------------------------------------------
' Layout Constants
'
' !$variable_name ?= "variable_value"
'---------------------------------------------------------

!$NODE_SEP ?= 75
!$RANK_SEP ?= 75
!$ROUND_CORNER ?= 10
!$MARGIN ?= 15
!$PADDING ?= 10

!$SHADOWING ?= %false()
!$LINE_TYPE ?= "ortho"
!$LINE_COLOR ?= $COLOR_TEXT
!$LINE_SIZE ?= 2

!$DEFAULT_TEXT_ALIGNMENT ?= "center"


'---------------------------------------------------------
' Container / Boundary Constants
'---------------------------------------------------------

!$RECTANGLE_BORDER_COLOR ?= $COLOR_NONE

'---------------------------------------------------------
' Legend Functions
'---------------------------------------------------------

' legend right
' |= TOGAF Category |= Color |
' | <back:E8DAEF>      </back> | External System |
' | <back:D6EAF8>      </back> | Logical Component / Service |
' | <back:FCF3CF>      </back> | Business Information Authority |
' endlegend
' --- End Import: src/libs/stdlib/vars/_layout.puml ---


' --- Importing: src/libs/stdlib/vars/_icons.puml ---

'---------------------------------------------------------
' Icon Constants
'
' !$variable_name ?= "variable_value"
'---------------------------------------------------------


'Actors
!$ACTOR_STYLE ?= awesome

!$ACTOR_BORDER_COLOR ?= "#0D47A1"
!$ACTOR_BORDER_SIZE ?= 3
!$ACTOR_BACKGROUND_COLOR ?= "#90CAF9"

' --- End Import: src/libs/stdlib/vars/_icons.puml ---



' --- Importing: src/libs/stdlib/vars/_title.puml ---


'---------------------------------------------------------
' Title Constants
'
' !$variable_name ?= "variable_value"
'---------------------------------------------------------

component "themes/common/_title :: called"

!$FONT_COLOR_TITLE ?= $COLOR_TEXT:
!$FONT_STYLE_TITLE ?= "bold"

!$BACKGROUND_COLOR_TITLE ?= $COLOR_PRIMARY_LIGHT
!$HORIZONTAL_ALIGNMENT_TITLE ?= "center"

!$MARGIN_TITLE ?= 20
!$PADDING_TITLE ?= 15
!$ROUND_CORNER_TITLE ?= $ROUND_CORNER

!$LINE_COLOR_TITLE ?= $LINE_COLOR
!$LINE_SIZE_TITLE ?= $LINE_SIZE

' --- End Import: src/libs/stdlib/vars/_title.puml ---


' --- End Import: src/libs/stdlib/vars/index.puml ---

' --- Importing: src/libs/togaf/vars/index.puml ---
' src/themes/togaf/index.puml
' Module Entry Point: TOGAF Theme Variables

' --- Importing: src/libs/togaf/vars/_colors.puml ---
' src/themes/togaf/_colors.puml

!$TOGAF_THEME_ENABLED ?= %false()


'Use Default TOGAF Colours
!$TOGAF_COLOR_BUSINESS ?= $COLOR_WARNING
!$TOGAF_COLOR_LOGICAL ?= $COLOR_PRIMARY
!$TOGAF_COLOR_DEPLOYMENT ?= "#FAD7A0"
!$TOGAF_COLOR_TECHNOLOGY ?= $COLOR_SUCCESS
!$TOGAF_COLOR_EXTERNAL ?= "#E8DAEF"
' --- End Import: src/libs/togaf/vars/_colors.puml ---

' --- Importing: src/libs/togaf/vars/_fonts.puml ---
' src/themes/togaf/_fonts.puml


!if ($TOGAF_THEME_ENABLED)

!endif
' --- End Import: src/libs/togaf/vars/_fonts.puml ---

' --- End Import: src/libs/togaf/vars/index.puml ---

' --- Importing: src/libs/ontario-health/vars/index.puml ---
' src/themes/ontario-health/index.puml
' Module Entry Point: Ontario Health Theme Variables

' --- Importing: src/libs/ontario-health/vars/_colors.puml ---
' src/themes/ontario-health/_colors.puml

!$OH_THEME_ENABLED ?= %false()


'Set OH Colours

!$OH_COLOR_PRIMARY ?= "#D6EAF8"
!$OH_COLOR_PRIMARY_LIGHT ?= "#D6EAF8"
!$OH_COLOR_PRIMARY_DARK ?= "#D6EAF8"

!$OH_COLOR_WARNING ?= "#FCF3CF"
!$OH_COLOR_WARNING_LIGHT ?= "#FCF3CF"
!$OH_COLOR_WARNING_DARK ?= "#FCF3CF"

!$OH_COLOR_SUCCESS ?= "#D5F5E3"
!$OH_COLOR_SUCCESS_LIGHT ?= "#D5F5E3"
!$OH_COLOR_SUCCESS_DARK ?= "#D5F5E3"

!$OH_COLOR_ERROR ?= "Red"
!$OH_COLOR_ERROR_LIGHT ?= "Red"
!$OH_COLOR_ERROR_DARK ?= "Red"

!$OH_COLOR_TEXT ?= "#000000"
!$OH_COLOR_BORDER ?= "#5D6D7E"


'Set OH Colours to TOGAF
!$OH_COLOR_BUSINESS ?= $OH_COLOR_WARNING
!$OH_COLOR_LOGICAL ?= $OH_COLOR_PRIMARY
!$OH_COLOR_DEPLOYMENT ?= "#FAD7A0"
!$OH_COLOR_TECHNOLOGY ?= $OH_COLOR_SUCCESS
!$OH_COLOR_EXTERNAL ?= "#E8DAEF"
' --- End Import: src/libs/ontario-health/vars/_colors.puml ---

' --- Importing: src/libs/ontario-health/vars/_fonts.puml ---
' src/themes/ontario-health/_fonts.puml
' --- End Import: src/libs/ontario-health/vars/_fonts.puml ---

' --- Importing: src/libs/ontario-health/vars/_layout.puml ---


!if ($OH_THEME_ENABLED)

'---------------------------------------------------------
' Title Constants
'---------------------------------------------------------

!$OH_MARGIN_TITLE = 20
!$OH_PADDING_TITLE = 15
!$OH_ROUND_CORNER_TITLE = 0

!$OH_LINE_COLOR_TITLE = $OH_COLOR_PRIMARY_DARK
!$OH_LINE_SIZE_TITLE = 5

!endif
' --- End Import: src/libs/ontario-health/vars/_layout.puml ---

' --- End Import: src/libs/ontario-health/vars/index.puml ---


'STEP 2 :: COMPONENTS includes
' --- Importing: src/libs/stdlib/components/index.puml ---
' --- End Import: src/libs/stdlib/components/index.puml ---

' --- Importing: src/libs/togaf/components/index.puml ---
' src/libraries/togaf/index.puml
' Module Entry Point: Libraries / TOGAF Component Pack 


' --- Importing: src/libs/togaf/components/_functions.puml ---
' src/libraries/togaf/_functions.puml

'---------------------------------------------------------
' Helper Functions for TOGAF library integration
'---------------------------------------------------------

'!function $togaf_layer_name($tg_name)
'  !if ($tg_name == "technology")
'
'  !return $first + " " + $last
'!endfunction

!function $togaf_layer_color($state)
  !if ($state == "success")
    !return "Green"
  !else
    !return "Red"
  !endif
!endfunction

' %get_variable_value
' %set_variable_value
' %upper

' %invoke_procedure($wrapper)
' %call_user_func

' %boolval

' !unquoted procedure 
' !unquoted function  
' --- End Import: src/libs/togaf/components/_functions.puml ---


' --- Importing: src/libs/togaf/components/_business.puml ---
' --- End Import: src/libs/togaf/components/_business.puml ---

' --- Importing: src/libs/togaf/components/_logical.puml ---

' component "Enterprise Identity Provider" as SBB01 #D6EAF8
' cloud "Identity Provider" as LC01 #E8DAEF
' database "PanelApp Data Source" as LC06 #D6EAF8
' node "REST API Pod" as DC01 #FAD7A0


' sprite $bProcess jar:archimate/business-process
' sprite $aService jar:archimate/application-service

' SHAPE CAPTION as ALIAS SPRITE COLOR
' rectangle "Document\nManagement\nSystem" as DMS <<$aComponent>> #Application
' --- End Import: src/libs/togaf/components/_logical.puml ---

' --- Importing: src/libs/togaf/components/_deployment.puml ---
' --- End Import: src/libs/togaf/components/_deployment.puml ---

' --- Importing: src/libs/togaf/components/_technology.puml ---
' --- End Import: src/libs/togaf/components/_technology.puml ---

' --- End Import: src/libs/togaf/components/index.puml ---

' --- Importing: src/libs/ontario-health/components/index.puml ---
' src/libraries/ontario-health/index.puml
' Module Entry Point: Libraries / Ontario Health Component Pack 

' --- Importing: src/libs/ontario-health/components/_patterns.puml ---
' --- End Import: src/libs/ontario-health/components/_patterns.puml ---

' --- Importing: src/libs/ontario-health/components/_sbbs.puml ---
' --- End Import: src/libs/ontario-health/components/_sbbs.puml ---

' --- End Import: src/libs/ontario-health/components/index.puml ---


'STEP 3 :: THEME includes
' --- Importing: src/libs/stdlib/theme/index.puml ---

' THIS FILE SHOULD BE BLANK
' --- End Import: src/libs/stdlib/theme/index.puml ---

' --- Importing: src/libs/togaf/theme/index.puml ---

!if ($TOGAF_THEME_ENABLED)

'Use Default TOGAF Colours
!$TOGAF_COLOR_BUSINESS ?= $COLOR_WARNING
!$TOGAF_COLOR_LOGICAL ?= $COLOR_PRIMARY
!$TOGAF_COLOR_DEPLOYMENT ?= "#FAD7A0"
!$TOGAF_COLOR_TECHNOLOGY ?= $COLOR_SUCCESS
!$TOGAF_COLOR_EXTERNAL ?= "#E8DAEF"


!endif
' --- End Import: src/libs/togaf/theme/index.puml ---

' --- Importing: src/libs/ontario-health/theme/index.puml ---

!if ($OH_THEME_ENABLED)

'Set OH Colours

!$COLOR_PRIMARY = $OH_COLOR_PRIMARY
!$COLOR_PRIMARY_LIGHT = $OH_COLOR_PRIMARY_LIGHT
!$COLOR_PRIMARY_DARK = $OH_COLOR_PRIMARY_DARK

!$COLOR_WARNING = $OH_COLOR_WARNING
!$COLOR_WARNING_LIGHT = $OH_COLOR_WARNING_LIGHT
!$COLOR_WARNING_DARK = $OH_COLOR_WARNING_DARK

!$COLOR_SUCCESS = $OH_COLOR_SUCCESS
!$COLOR_SUCCESS_LIGHT = $OH_COLOR_SUCCESS_LIGHT
!$COLOR_SUCCESS_DARK = $OH_COLOR_SUCCESS_DARK

!$COLOR_ERROR = $OH_COLOR_ERROR
!$COLOR_ERROR_LIGHT = $OH_COLOR_ERROR_LIGHT
!$COLOR_ERROR_DARK = $OH_COLOR_ERROR_DARK

!$COLOR_TEXT = $OH_COLOR_TEXT
!$COLOR_BORDER ?= $OH_COLOR_BORDER


'If there are a lot of variables, this could be moved into a separate _togaf.puml file

!if ($TOGAF_THEME_ENABLED)

    'Set OH Colours to TOGAF
    !$TOGAF_COLOR_BUSINESS ?= $OH_COLOR_WARNING
    !$TOGAF_COLOR_LOGICAL ?= $OH_COLOR_PRIMARY
    !$TOGAF_COLOR_DEPLOYMENT ?= "#FAD7A0"
    !$TOGAF_COLOR_TECHNOLOGY ?= $OH_COLOR_SUCCESS
    !$TOGAF_COLOR_EXTERNAL ?= "#E8DAEF"

!endif 'TOGAF_THEME_ENABLED

!endif
' --- End Import: src/libs/ontario-health/theme/index.puml ---


'STEP 4 :: Skin Params includes
' --- Importing: src/libs/stdlib/skinparam/index.puml ---

'---------------------------------------------------------
' skinparam Initialization
'---------------------------------------------------------


' skinparam linetype polyline
' skinparam linetype ortho

skinparam shadowing $SHADOWING
skinparam linetype $LINE_TYPE
skinparam defaultTextAlignment $DEFAULT_TEXT_ALIGNMENT


skinparam nodesep $NODE_SEP
skinparam ranksep $RANK_SEP


skinparam rectangleBorderColor $RECTANGLE_BORDER_COLOR

skinparam actorStyle $ACTOR_STYLE
skinparam actorBorderColor $ACTOR_BORDER_COLOR
skinparam actorBorderThickness $ACTOR_BORDER_SIZE
skinparam actorBackgroundColor $ACTOR_BACKGROUND_COLOR
' --- End Import: src/libs/stdlib/skinparam/index.puml ---

' --- Importing: src/libs/togaf/skinparam/index.puml ---

'---------------------------------------------------------
' skinparam Initialization
'---------------------------------------------------------

' --- End Import: src/libs/togaf/skinparam/index.puml ---

' --- Importing: src/libs/ontario-health/skinparam/index.puml ---

'---------------------------------------------------------
' skinparam Initialization
'---------------------------------------------------------

' --- End Import: src/libs/ontario-health/skinparam/index.puml ---


'STEP 5 :: STYLES includes
' --- Importing: src/libs/stdlib/styles/index.puml ---


' --- Importing: src/libs/stdlib/styles/_title.puml ---



'---------------------------------------------------------
' Title Styles
'---------------------------------------------------------

!procedure Write_Lib_Style_Stdlib_Title()

<style>
title {
    BackgroundColor $BACKGROUND_COLOR_TITLE
    HorizontalAlignment $HORIZONTAL_ALIGNMENT_TITLE
    FontSize $FONT_SIZE_TITLE
    FontColor $FONT_COLOR_TITLE
    FontStyle $FONT_STYLE_TITLE
    
    LineColor $LINE_COLOR_TITLE
    LineThickness $LINE_SIZE_TITLE

    RoundCorner $ROUND_CORNER_TITLE
    Margin $MARGIN_TITLE
    Padding $PADDING_TITLE
}
</style>

!endprocedure


'---------------------------------------------------------
' Title Element
'---------------------------------------------------------
' --- End Import: src/libs/stdlib/styles/_title.puml ---


!procedure Load_Lib_Styles_Stdlib()

    Write_Lib_Style_Stdlib_Title()
    
!endprocedure
' --- End Import: src/libs/stdlib/styles/index.puml ---

' --- Importing: src/libs/togaf/styles/index.puml ---
!procedure Load_Lib_Styles_Togaf()
!if ($TOGAF_THEME_ENABLED)

!endif

!endprocedure 
' --- End Import: src/libs/togaf/styles/index.puml ---

' --- Importing: src/libs/ontario-health/styles/index.puml ---


!procedure Load_Lib_Styles_OntarioHealth()

    !if ($OH_THEME_ENABLED)

    !endif
!endprocedure 
' --- End Import: src/libs/ontario-health/styles/index.puml ---


'STEP 6 :: Add to Load_Lib_Styles_All

!procedure Load_Lib_Styles_All()

    Load_Lib_Styles_Stdlib()
    Load_Lib_Styles_Togaf()
    Load_Lib_Styles_OntarioHealth()

!endprocedure

' --- End Import: src/libs/index.puml ---

' --- End Import: src/index.puml ---

