' ========================================================
' Combined PlantUML Library Bundle (SASS-Style Compilation)
' Generated on: 2026-09-11 10:57:05 EDT
' ========================================================

' src/all.puml
' Module Entry Point: OH + TOGAF Component Pack

' --- Importing: src/index.puml ---
' src/index.puml
' Module Entry Point: OH + TOGAF Component Pack

' --- Importing: src/themes/index.puml ---
' src/themes/index.puml

' Module Entry Point: Constants, Procedure and Functions
' --- Importing: src/themes/common/index.puml ---
' src/themes/common/index.puml
' Module Entry Point: Common Theme Variables

' --- Importing: src/themes/common/_colors.puml ---
' src/themes/common/_colors.puml

'---------------------------------------------------------
' Color Constants
'
' !$variable_name ?= "variable_value"
'---------------------------------------------------------

!$COLOR_TRANSPARENT = "#FFFFFF00"
!$COLOR_NONE ?= $COLOR_TRANSPARENT

!$COLOR_PRIMARY ?= "#D6EAF8"
!$COLOR_PRIMARY_LIGHT ?= "#D6EAF8"
!$COLOR_PRIMARY_DARK ?= "#D6EAF8"

!$COLOR_WARNING ?= "#FCF3CF"
!$COLOR_WARNING_LIGHT ?= "#FCF3CF"
!$COLOR_WARNING_DARK ?= "#FCF3CF"

!$COLOR_SUCCESS ?= "#D5F5E3"
!$COLOR_SUCCESS_LIGHT ?= "#D5F5E3"
!$COLOR_SUCCESS_DARK ?= "#D5F5E3"

!$COLOR_ERROR ?= "Red"
!$COLOR_ERROR_LIGHT ?= "Red"
!$COLOR_ERROR_DARK ?= "Red"

!$COLOR_TEXT ?= "#000000"
!$COLOR_BORDER ?= "#5D6D7E"
' --- End Import: src/themes/common/_colors.puml ---

' --- Importing: src/themes/common/_fonts.puml ---
' src/themes/common/_fonts.puml

'---------------------------------------------------------
' Font Constants
'
' !$variable_name ?= "variable_value"
'---------------------------------------------------------

!$FONT_NAME ?= "Segoe UI"
!$FONT_SIZE ?= 12
!$FONT_SIZE_TITLE ?= 18
!$FONT_SIZE_LEGEND ?= 11
!$FONT_SIZE_ARROW ?= 11

!$FONT_COLOR ?= $COLOR_TEXT
' --- End Import: src/themes/common/_fonts.puml ---


' --- Importing: src/themes/common/_borders.puml ---
' src/themes/common/_borders.puml

'---------------------------------------------------------
' Border Constants
'
' !$variable_name ?= "variable_value"
'---------------------------------------------------------

!$BORDER_THICKNESS ?= 1
!$BORDER_THICKNESS_BOLD ?= 2
!$BORDER_THICKNESS_POD ?= 2
' --- End Import: src/themes/common/_borders.puml ---


' --- Importing: src/themes/common/_layout.puml ---
' src/themes/common/_layout.puml

'---------------------------------------------------------
' Layout Constants
'
' !$variable_name ?= "variable_value"
'---------------------------------------------------------

!$NODE_SEP ?= 75
!$RANK_SEP ?= 75
!$ROUND_CORNER ?= 10
!$MARGIN ?= 15
!$PADDING ?= 10



!$SHADOWING ?= %false()
!$LINETYPE ?= "ortho"

!$DEFAULT_TEXT_ALIGNMENT ?= "center"


'---------------------------------------------------------
' Container / Boundary Constants
'---------------------------------------------------------

!$RECTANGLE_BORDER_COLOR ?= $COLOR_NONE

'---------------------------------------------------------
' Legend Functions
'---------------------------------------------------------

' legend right
' |= TOGAF Category |= Color |
' | <back:E8DAEF>      </back> | External System |
' | <back:D6EAF8>      </back> | Logical Component / Service |
' | <back:FCF3CF>      </back> | Business Information Authority |
' endlegend
' --- End Import: src/themes/common/_layout.puml ---


' --- Importing: src/themes/common/_icons.puml ---
' src/themes/common/_icons.puml

'---------------------------------------------------------
' Icon Constants
'
' !$variable_name ?= "variable_value"
'---------------------------------------------------------


'Actors
!$ACTOR_STYLE ?= awesome

!$ACTOR_BORDER_COLOR ?= "#0D47A1"
!$ACTOR_BORDER_SIZE ?= 3
!$ACTOR_BACKGROUND_COLOR ?= "#90CAF9"

' --- End Import: src/themes/common/_icons.puml ---



' --- Importing: src/themes/common/_title.puml ---


'---------------------------------------------------------
' Title Constants
'
' !$variable_name ?= "variable_value"
'---------------------------------------------------------

!$FONT_COLOR_TITLE ?= $COLOR_PRIMARY
!$FONT_STYLE_TITLE ?= "bold"

!$BACKGROUND_COLOR_TITLE ?= $COLOR_PRIMARY_LIGHT
!$HORIZONTAL_ALIGNMENT_TITLE ?= "center"

!$MARGIN_TITLE ?= 20
!$PADDING_TITLE ?= 15
!$ROUND_CORNER_TITLE ?= $ROUND_CORNER

!$LINE_COLOR_TITLE ?= $LINE_COLOR
!$LINE_SIZE_TITLE ?= $LINE_SIZE



'---------------------------------------------------------
' Title Styles
'---------------------------------------------------------

!procedure WriteThemeStyle_Common_Title()
<style>
title {
    BackgroundColor $BACKGROUND_COLOR_TITLE
    HorizontalAlignment $HORIZONTAL_ALIGNMENT_TITLE
    FontSize $FONT_SIZE_TITLE
    FontColor $FONT_COLOR_TITLE
    FontStyle $FONT_STYLE_TITLE
    
    LineColor $LINE_COLOR_TITLE
    LineThickness $LINE_SIZE_TITLE

    RoundCorner $ROUND_CORNER_TITLE
    Margin $MARGIN_TITLE
    Padding $PADDING_TITLE
}
</style>

!endprocedure


'---------------------------------------------------------
' Title Element
'---------------------------------------------------------
' --- End Import: src/themes/common/_title.puml ---


' --- Importing: src/themes/common/_skinparam.puml ---
' src/themes/common/_layout.puml

'---------------------------------------------------------
' skinparam Initialization
'---------------------------------------------------------


' skinparam linetype polyline
' skinparam linetype ortho

skinparam shadowing $SHADOWING
skinparam linetype $LINETYPE
skinparam defaultTextAlignment $DEFAULT_TEXT_ALIGNMENT


skinparam nodesep $NODE_SEP
skinparam ranksep $RANK_SEP


skinparam rectangleBorderColor $RECTANGLE_BORDER_COLOR

skinparam actorStyle $ACTOR_STYLE
skinparam actorBorderColor $ACTOR_BORDER_COLOR
skinparam actorBorderThickness $ACTOR_BORDER_SIZE
skinparam actorBackgroundColor $ACTOR_BACKGROUND_COLOR
' --- End Import: src/themes/common/_skinparam.puml ---

' --- End Import: src/themes/common/index.puml ---

' --- Importing: src/themes/togaf/index.puml ---
' src/themes/togaf/index.puml
' Module Entry Point: TOGAF Theme Variables

' --- Importing: src/themes/togaf/_colors.puml ---
' src/themes/togaf/_colors.puml

!$TOGAF_THEME_ENABLED ?= %true()

!if ($TOGAF_THEME_ENABLED)

'Use Default TOGAF Colours
!$COLOR_BUSINESS ?= $COLOR_WARNING
!$COLOR_LOGICAL ?= $COLOR_PRIMARY
!$COLOR_DEPLOYMENT ?= "#FAD7A0"
!$COLOR_TECHNOLOGY ?= $COLOR_SUCCESS
!$COLOR_EXTERNAL ?= "#E8DAEF"


' Functional Capabilities = #FCF3CF (light yellow)
' Logical Components / Services = #D6EAF8 (light blue)
' External Systems = #E8DAEF (light purple)
' Deployment Components = #FAD7A0 (light orange)
' Technology Products / Platforms = #D5F5E3 (light green)

!endif
' --- End Import: src/themes/togaf/_colors.puml ---

' --- Importing: src/themes/togaf/_fonts.puml ---
' src/themes/togaf/_fonts.puml


!if ($TOGAF_THEME_ENABLED)

!endif
' --- End Import: src/themes/togaf/_fonts.puml ---

' --- End Import: src/themes/togaf/index.puml ---

' --- Importing: src/themes/ontario-health/index.puml ---
' src/themes/ontario-health/index.puml
' Module Entry Point: Ontario Health Theme Variables

' --- Importing: src/themes/ontario-health/_colors.puml ---
' src/themes/ontario-health/_colors.puml

!$OH_THEME_ENABLED ?= %true()

!if ($OH_THEME_ENABLED)

'Set OH Colours

!$COLOR_PRIMARY ?= "#D6EAF8"
!$COLOR_PRIMARY_LIGHT ?= "#D6EAF8"
!$COLOR_PRIMARY_DARK ?= "#D6EAF8"

!$COLOR_WARNING ?= "#FCF3CF"
!$COLOR_WARNING_LIGHT ?= "#FCF3CF"
!$COLOR_WARNING_DARK ?= "#FCF3CF"

!$COLOR_SUCCESS ?= "#D5F5E3"
!$COLOR_SUCCESS_LIGHT ?= "#D5F5E3"
!$COLOR_SUCCESS_DARK ?= "#D5F5E3"

!$COLOR_ERROR ?= "Red"
!$COLOR_ERROR_LIGHT ?= "Red"
!$COLOR_ERROR_DARK ?= "Red"

!$COLOR_TEXT ?= "#000000"
!$COLOR_BORDER ?= "#5D6D7E"


'If there are a lot of variables, this could be moved into a separate _togaf.puml file

!if ($TOGAF_THEME_ENABLED)

    'Set OH Colours to TOGAF
    !$COLOR_BUSINESS ?= $COLOR_WARNING
    !$COLOR_LOGICAL ?= $COLOR_PRIMARY
    !$COLOR_DEPLOYMENT ?= "#FAD7A0"
    !$COLOR_TECHNOLOGY ?= $COLOR_SUCCESS
    !$COLOR_EXTERNAL ?= "#E8DAEF"
!endif 'TOGAF_THEME_ENABLED

!endif
' --- End Import: src/themes/ontario-health/_colors.puml ---

' --- Importing: src/themes/ontario-health/_fonts.puml ---
' src/themes/ontario-health/_fonts.puml
' --- End Import: src/themes/ontario-health/_fonts.puml ---

' --- End Import: src/themes/ontario-health/index.puml ---



' Module Entry Point: Sytles
' --- Importing: src/themes/common/styles/index.puml ---



!procedure LoadThemeStyles_Common()

    WriteThemeStyle_Common_Title()
    
!endprocedure
' --- End Import: src/themes/common/styles/index.puml ---

' --- Importing: src/themes/togaf/styles/index.puml ---
!procedure LoadThemeStyles_Togaf()
!if ($TOGAF_THEME_ENABLED)

!endif

!endprocedure 
' --- End Import: src/themes/togaf/styles/index.puml ---

' --- Importing: src/themes/ontario-health/styles/index.puml ---


!procedure LoadThemeStyles_OntarioHealth()

    !if ($OH_THEME_ENABLED)

    !endif
!endprocedure 
' --- End Import: src/themes/ontario-health/styles/index.puml ---


!procedure LoadThemeStyles_All()

    LoadThemeStyles_Common()
    LoadThemeStyles_Togaf()
    LoadThemeStyles_OntarioHealth()

!endprocedure
' --- End Import: src/themes/index.puml ---

' --- Importing: src/libraries/index.puml ---
' src/libraries/index.puml
' Module Entry Point: Libraries

' --- Importing: src/libraries/stdlib/index.puml ---
' src/libraries/stdlib/index.puml
' Module Entry Point: Libraries / Standard PlantUML Component Pack

' --- End Import: src/libraries/stdlib/index.puml ---

' --- Importing: src/libraries/togaf/index.puml ---
' src/libraries/togaf/index.puml
' Module Entry Point: Libraries / TOGAF Component Pack 


' --- Importing: src/libraries/togaf/_functions.puml ---
' src/libraries/togaf/_functions.puml

'---------------------------------------------------------
' Helper Functions for TOGAF library integration
'---------------------------------------------------------

'!function $togaf_layer_name($tg_name)
'  !if ($tg_name == "technology")
'
'  !return $first + " " + $last
'!endfunction

!function $togaf_layer_color($state)
  !if ($state == "success")
    !return "Green"
  !else
    !return "Red"
  !endif
!endfunction

' %get_variable_value
' %set_variable_value
' %upper

' %invoke_procedure($wrapper)
' %call_user_func

' %boolval

' !unquoted procedure 
' !unquoted function  
' --- End Import: src/libraries/togaf/_functions.puml ---


' --- Importing: src/libraries/togaf/_business.puml ---
' --- End Import: src/libraries/togaf/_business.puml ---

' --- Importing: src/libraries/togaf/_logical.puml ---

' component "Enterprise Identity Provider" as SBB01 #D6EAF8
' cloud "Identity Provider" as LC01 #E8DAEF
' database "PanelApp Data Source" as LC06 #D6EAF8
' node "REST API Pod" as DC01 #FAD7A0


' sprite $bProcess jar:archimate/business-process
' sprite $aService jar:archimate/application-service

' SHAPE CAPTION as ALIAS SPRITE COLOR
' rectangle "Document\nManagement\nSystem" as DMS <<$aComponent>> #Application
' --- End Import: src/libraries/togaf/_logical.puml ---

' --- Importing: src/libraries/togaf/_deployment.puml ---
' --- End Import: src/libraries/togaf/_deployment.puml ---

' --- Importing: src/libraries/togaf/_technology.puml ---
' --- End Import: src/libraries/togaf/_technology.puml ---

' --- End Import: src/libraries/togaf/index.puml ---

' --- Importing: src/libraries/ontario-health/index.puml ---
' src/libraries/ontario-health/index.puml
' Module Entry Point: Libraries / Ontario Health Component Pack 

' --- Importing: src/libraries/ontario-health/_patterns.puml ---
' --- End Import: src/libraries/ontario-health/_patterns.puml ---

' --- Importing: src/libraries/ontario-health/_sbbs.puml ---
' --- End Import: src/libraries/ontario-health/_sbbs.puml ---

' --- End Import: src/libraries/ontario-health/index.puml ---

' --- End Import: src/libraries/index.puml ---

' --- End Import: src/index.puml ---

