' ========================================================
' Combined PlantUML Library Bundle (SASS-Style Compilation)
' Bundle Name: Theme: ontariohealth
' Generated on: 2026-10-08 16:29:40 EDT
' Build Commit Hash: a4148a6f51205a49bf02341650bb2d2e4ad4ba7b
' Build Commit Comment: refactoring fixes
' ========================================================




'STEP 1 :: VARS includes
' --- Importing: src/themes/ontariohealth/vars/index.puml ---
' src/themes/ontario-health/index.puml
' Module Entry Point: Ontario Health Theme Variables

' --- Importing: src/themes/ontariohealth/vars/_index.puml ---


' --- End Import: src/themes/ontariohealth/vars/_index.puml ---

' --- Importing: src/themes/ontariohealth/vars/_colors.puml ---

'---------------------------------------------------------
' Color Constants
'---------------------------------------------------------

!$COLOR_OH_LABEL ?= "#4D4D4D"
!$COLOR_OH_PLACEHOLDER ?= "#737373"


'$COLOR_OH_BRAND_HOVER ?= "#049A5"

'FOCUS_COLOR ?= "#F2FBFF"
'ACCENT_COLOR ?= "#00B2E3" 
'BRIGHT BLUE


!$COLOR_OH_PRIMARY ?= "#047BC1"
!$COLOR_OH_PRIMARY_LIGHT ?= "#D6EAF8"
!$COLOR_OH_PRIMARY_DARK ?= "#023451"

!$COLOR_OH_WARNING ?= "#FCAF17"
!$COLOR_OH_WARNING_LIGHT ?= "#EFB243"
!$COLOR_OH_WARNING_DARK ?= "#FFFAEB"
'FFFAEB

!$COLOR_OH_SUCCESS ?= "#118847"
!$COLOR_OH_SUCCESS_LIGHT ?= "#EAF5EA"
!$COLOR_OH_SUCCESS_DARK ?= "#0F7C41"

!$COLOR_OH_ERROR ?= "#CD0000"
!$COLOR_OH_ERROR_LIGHT ?= "#FCEFF0"
!$COLOR_OH_ERROR_DARK ?= "#8a0101"

'! $COLOR_OH_EMPHASIS ?= "#9333EA"
'! $COLOR_OH_EMPHASIS_LIGHT ?= "#"
'! $COLOR_OH_EMPHASIS_DARK ?= "#"

!$COLOR_OH_TEXT ?= "#1A1A1A"
!$COLOR_OH_BORDER ?= "#5D6D7E"


'Set OH Colours to TOGAF
!$COLOR_OH_BUSINESS ?= $COLOR_OH_WARNING
!$COLOR_OH_LOGICAL ?= $COLOR_OH_PRIMARY
!$COLOR_OH_DEPLOYMENT ?= "#FAD7A0"
!$COLOR_OH_TECHNOLOGY ?= $COLOR_OH_SUCCESS
!$COLOR_OH_EXTERNAL ?= "#E8DAEF"


!$COLOR_OH_MOTIVATION_LIGHT ?= "#F1E3F2"
!$COLOR_OH_MOTIVATION_DARK ?= "#B975B7"
!$COLOR_OH_STRATEGY_LIGHT ?= "#F8E5C3"
!$COLOR_OH_STRATEGY_DARK ?= "#EFB243"
!$COLOR_OH_BUSINESS_LIGHT ?= "#FFFDC4"
!$COLOR_OH_BUSINESS_DARK ?= "#FFD440"
!$COLOR_OH_APPLICATION_LIGHT ?= "#C5EEFA"
!$COLOR_OH_APPLICATION_DARK ?= "#3193CC"
!$COLOR_OH_TECHNOLOGY_LIGHT ?= "#D1EFD4"
!$COLOR_OH_TECHNOLOGY_DARK ?= "#39B54A"
!$COLOR_OH_IMPLEMENTATION_LIGHT ?= "#FEE1D9"
!$COLOR_OH_IMPLEMENTATION_DARK ?= "#F15A22"
!$COLOR_OH_HIGHLIGHTED_LIGHT ?= "#CFEDED"
!$COLOR_OH_HIGHLIGHTED_DARK ?= "#0050EF"
!$COLOR_OH_NEW_LIGHT ?= "#DDEDC7"
!$COLOR_OH_NEW_DARK ?= "#005700"

' --- End Import: src/themes/ontariohealth/vars/_colors.puml ---

' --- Importing: src/themes/ontariohealth/vars/_fonts.puml ---
' --- End Import: src/themes/ontariohealth/vars/_fonts.puml ---

' --- Importing: src/themes/ontariohealth/vars/_layout.puml ---


'---------------------------------------------------------
' Layout Constants
'---------------------------------------------------------



' --- End Import: src/themes/ontariohealth/vars/_layout.puml ---


' --- Importing: src/themes/ontariohealth/vars/_title.puml ---
'---------------------------------------------------------
' Title Constants
'---------------------------------------------------------

!$MARGIN_OH_TITLE ?= 20
!$PADDING_OH_TITLE ?= 15
!$ROUND_OH_CORNER_TITLE ?= 0


!$COLOR_OH_BACKGROUND_TITLE ?= "PRIMARY_DARK"
!$COLOR_OH_FONT_TITLE ?= "AUTO"
    
!$COLOR_OH_LINE_TITLE ?= "CURRENT" 
' --- End Import: src/themes/ontariohealth/vars/_title.puml ---

' --- End Import: src/themes/ontariohealth/vars/index.puml ---


'STEP 2 :: COMPONENTS includes
' --- Importing: src/themes/ontariohealth/components/index.puml ---
' src/libraries/ontario-health/index.puml
' Module Entry Point: Libraries / Ontario Health Component Pack 

' --- Importing: src/themes/ontariohealth/components/_title.puml ---



' --- End Import: src/themes/ontariohealth/components/_title.puml ---

' --- Importing: src/themes/ontariohealth/components/_patterns.puml ---
' --- End Import: src/themes/ontariohealth/components/_patterns.puml ---

' --- Importing: src/themes/ontariohealth/components/_sbbs.puml ---
' --- End Import: src/themes/ontariohealth/components/_sbbs.puml ---

' --- End Import: src/themes/ontariohealth/components/index.puml ---


'STEP 3 :: THEME includes
' --- Importing: src/themes/ontariohealth/theme/index.puml ---
' src/themes/ontario-health/index.puml
' Module Entry Point: Ontario Health Theme Variables

' --- Importing: src/themes/ontariohealth/theme/_colors.puml ---
'---------------------------------------------------------
' Color Constants Applied
'---------------------------------------------------------


!procedure Preload_Theme_OntarioHealth_Colors()

'Set OH Colours

!$COLOR_PRIMARY = $COLOR_OH_PRIMARY
!$COLOR_PRIMARY_LIGHT = $COLOR_OH_PRIMARY_LIGHT
!$COLOR_PRIMARY_DARK = $COLOR_OH_PRIMARY_DARK

!$COLOR_WARNING = $COLOR_OH_WARNING
!$COLOR_WARNING_LIGHT = $COLOR_OH_WARNING_LIGHT
!$COLOR_WARNING_DARK = $COLOR_OH_WARNING_DARK

!$COLOR_SUCCESS = $COLOR_OH_SUCCESS
!$COLOR_SUCCESS_LIGHT = $COLOR_OH_SUCCESS_LIGHT
!$COLOR_SUCCESS_DARK = $COLOR_OH_SUCCESS_DARK

!$COLOR_ERROR = $COLOR_OH_ERROR
!$COLOR_ERROR_LIGHT = $COLOR_OH_ERROR_LIGHT
!$COLOR_ERROR_DARK = $COLOR_OH_ERROR_DARK

!$COLOR_TEXT = $COLOR_OH_TEXT
!$COLOR_BORDER ?= $COLOR_OH_BORDER


!$COLOR_DISABLED_DARK = $COLOR_OH_LABEL
!$COLOR_DISABLED = $COLOR_OH_PLACEHOLDER



'If there are a lot of variables, this could be moved into a separate _togaf.puml file


!if ($TOGAF_LIB_ENABLED)

    'This is the surface colour

    !$COLOR_MOTIVATION_LIGHT ?= $COLOR_OH_MOTIVATION_LIGHT
    !$COLOR_MOTIVATION_DARK ?= $COLOR_OH_MOTIVATION_DARK

    !$COLOR_STRATEGY_LIGHT ?= $COLOR_OH_STRATEGY_LIGHT
    !$COLOR_STRATEGY_DARK ?= $COLOR_OH_STRATEGY_DARK

    !$COLOR_BUSINESS_LIGHT ?= $COLOR_OH_BUSINESS_LIGHT
    !$COLOR_BUSINESS_DARK ?= $COLOR_OH_BUSINESS_DARK

    !$COLOR_APPLICATION_LIGHT ?= $COLOR_OH_APPLICATION_LIGHT
    !$COLOR_APPLICATION_DARK ?= $COLOR_OH_APPLICATION_DARK

    !$COLOR_TECHNOLOGY_LIGHT ?= $COLOR_OH_TECHNOLOGY_LIGHT
    !$COLOR_TECHNOLOGY_DARK ?= $COLOR_OH_TECHNOLOGY_DARK

    !$COLOR_IMPLEMENTATION_LIGHT ?= $COLOR_OH_IMPLEMENTATION_LIGHT
    !$COLOR_IMPLEMENTATION_DARK ?= $COLOR_OH_IMPLEMENTATION_DARK

    !$COLOR_HIGHLIGHTED_LIGHT ?= $COLOR_OH_HIGHLIGHTED_LIGHT
    !$COLOR_HIGHLIGHTED_DARK ?= $COLOR_OH_HIGHLIGHTED_DARK

    !$COLOR_NEW_LIGHT ?= $COLOR_OH_NEW_LIGHT
    !$COLOR_NEW_DARK ?= $COLOR_OH_NEW_DARK


!endif

!endprocedure

' --- End Import: src/themes/ontariohealth/theme/_colors.puml ---

' --- Importing: src/themes/ontariohealth/theme/_layout.puml ---

'---------------------------------------------------------
' Layout Constants Applied
'---------------------------------------------------------


!procedure Preload_Theme_OntarioHealth_Layout()


!endprocedure
' --- End Import: src/themes/ontariohealth/theme/_layout.puml ---

' --- Importing: src/themes/ontariohealth/theme/_title.puml ---


'---------------------------------------------------------
' Title Constants Applied
'---------------------------------------------------------


!procedure Preload_Theme_OntarioHealth_Title()

!$MARGIN_TITLE = $MARGIN_OH_TITLE
!$PADDING_TITLE = $PADDING_OH_TITLE

!$ROUND_CORNER_TITLE = $ROUND_OH_CORNER_TITLE

!$COLOR_BACKGROUND_TITLE = $COLOR_OH_BACKGROUND_TITLE
!$COLOR_FONT_TITLE = $COLOR_OH_FONT_TITLE
    
!$COLOR_LINE_TITLE = $COLOR_OH_LINE_TITLE 

!endprocedure

' --- End Import: src/themes/ontariohealth/theme/_title.puml ---



!procedure Preload_Theme_OntarioHealth()
    !if ($Is_Theme_Registered("OntarioHealth"))
        Preload_Theme_OntarioHealth_Colors()
        Preload_Theme_OntarioHealth_Layout()
        Preload_Theme_OntarioHealth_Title()
    !endif
!endprocedure
' --- End Import: src/themes/ontariohealth/theme/index.puml ---


'STEP 4 :: Skin Params includes
' --- Importing: src/themes/ontariohealth/skinparam/index.puml ---

'---------------------------------------------------------
' skinparam Initialization
'---------------------------------------------------------

!if ($SKINPARAM_ENABLED)



!endif
' --- End Import: src/themes/ontariohealth/skinparam/index.puml ---


'STEP 5 :: STYLES includes
' --- Importing: src/themes/ontariohealth/styles/index.puml ---


' --- Importing: src/themes/ontariohealth/styles/_title.puml ---


!procedure Write_Lib_Style_OntarioHealth_Title()

!endprocedure 
' --- End Import: src/themes/ontariohealth/styles/_title.puml ---





!procedure Load_Lib_Styles_THEME_OntarioHealth()

    !if ($Is_Theme_Registered("OntarioHealth"))
        Write_Lib_Style_OntarioHealth_Title()
    !endif
!endprocedure 
' --- End Import: src/themes/ontariohealth/styles/index.puml ---

