' src/themes/common/_borders.puml

'---------------------------------------------------------
' Border Constants
'
' !$variable_name ?= "variable_value"
'---------------------------------------------------------

!$BORDER_THICKNESS ?= 1
!$BORDER_THICKNESS_BOLD ?= 2
!$BORDER_THICKNESS_POD ?= 2
