' src/themes/common/_layout.puml

'---------------------------------------------------------
' Layout Constants
'---------------------------------------------------------

!$NODE_SEP      = 75
!$RANK_SEP      = 75
!$ROUND_CORNER  = 10