' src/themes/common/_layout.puml

'---------------------------------------------------------
' skinparam Initialization
'---------------------------------------------------------


' skinparam linetype polyline
' skinparam linetype ortho

skinparam shadowing $!SHADOWING
skinparam linetype $!LINETYPE
skinparam defaultTextAlignment $!DEFAULT_TEXT_ALIGNMENT


skinparam nodesep !$NODE_SEP
skinparam ranksep !$RANK_SEP


skinparam rectangleBorderColor !$RECTANGLE_BORDER_COLOR

skinparam actorStyle !$ACTOR_STYLE
skinparam actorBorderColor !$ACTOR_BORDER_COLOR
skinparam actorBorderSize !$ACTOR_BORDER_SIZE
skinparam actorBackgroundColor !$ACTOR_BACKGROUND_COLOR
