' src/themes/common/index.puml
' Module Entry Point: Common Theme Variables

!include _colors.puml
!include _fonts.puml

!include _borders.puml

!include _layout.puml

!include _icons.puml


!include _title.puml

!include _skinparam.puml