
'---------------------------------------------------------
' skinparam Initialization
'---------------------------------------------------------


' skinparam linetype polyline
' skinparam linetype ortho


skinparam linetype $LINE_TYPE
skinparam nodesep $NODE_SEP
skinparam ranksep $RANK_SEP

!if ($SKINPARAM_ENABLED)

skinparam shadowing $SHADOWING
skinparam defaultTextAlignment $DEFAULT_TEXT_ALIGNMENT

skinparam rectangleBorderColor $COLOR_BORDER_RECTANGLE

skinparam actorStyle $STYLE_ACTOR
skinparam actorBorderColor $COLOR_BORDER_ACTOR
skinparam actorBorderThickness $SIZE_BORDER_ACTOR
skinparam actorBackgroundColor $COLOR_BACKGROUND_ACTOR

!endif