' src/themes/togaf/_colors.puml

!$TOGAF_THEME_ENABLED ?= %false()


'Use Default TOGAF Colours
!$TOGAF_COLOR_BUSINESS ?= $COLOR_WARNING
!$TOGAF_COLOR_LOGICAL ?= $COLOR_PRIMARY
!$TOGAF_COLOR_DEPLOYMENT ?= "#FAD7A0"
!$TOGAF_COLOR_TECHNOLOGY ?= $COLOR_SUCCESS
!$TOGAF_COLOR_EXTERNAL ?= "#E8DAEF"
