' src/themes/togaf/_colors.puml



!$COLOR_TOGAF_MOTIVATION ?= "#CCCCFF"
!$COLOR_TOGAF_STRATEGY ?= "#F5DEAA"
!$COLOR_TOGAF_BUSINESS ?= "#FFFF99"
!$COLOR_TOGAF_APPLICATION ?= "#99FFFF"
!$COLOR_TOGAF_TECHNOLOGY ?= "#AFFFAF"
!$COLOR_TOGAF_IMPLEMENTATION ?= "#FFE0E0"
!$COLOR_TOGAF_HIGHLIGHTED ?= "#005DEF"
!$COLOR_TOGAF_NEW ?= "#005700"

