' src/themes/togaf/_colors.puml



!$TOGAF_COLOR_MOTIVATION ?= "#CCCCFF"
!$TOGAF_COLOR_STRATEGY ?= "#F5DEAA"
!$TOGAF_COLOR_BUSINESS ?= "#FFFF99"
!$TOGAF_COLOR_APPLICATION ?= "#99FFFF"
!$TOGAF_COLOR_TECHNOLOGY ?= "#AFFFAF"
!$TOGAF_COLOR_IMPLEMENTATION ?= "#FFE0E0"
!$TOGAF_COLOR_HIGHLIGHTED ?= "#005DEF"
!$TOGAF_COLOR_NEW ?= "#005700"
