
'---------------------------------------------------------
' Border Constants
'
' !$variable_name ?= "variable_value"
'---------------------------------------------------------

!$BORDER_THICKNESS ?= 1
!$BORDER_THICKNESS_BOLD ?= 2
!$BORDER_THICKNESS_POD ?= 2

!$BORDER_0 ?= 0
!$BORDER_1 ?= 1
!$BORDER_2 ?= 2
!$BORDER_3 ?= 3
!$BORDER_4 ?= 4
