'---------------------------------------------------------
' Darkening defaults
'---------------------------------------------------------

' Darkening default
!$DARKEN_DEFAULT_PERCENT = 20

' RGB luminance floor (0-255)
!$DARKNESS_THRESHOLD = 32


'---------------------------------------------------------
' Lightening defaults
'---------------------------------------------------------

' Lightening default
!$LIGHTEN_DEFAULT_PERCENT = 20

' RGB luminance ceiling (0-255)
!$LIGHTNESS_THRESHOLD = 223



'---------------------------------------------------------
' Color Constants
'
' !$variable_name ?= "variable_value"
'---------------------------------------------------------

!$COLOR_TRANSPARENT = "#FFFFFF00"
!$COLOR_NONE ?= $COLOR_TRANSPARENT

!$COLOR_PRIMARY ?= "#D6EAF8"
!$COLOR_PRIMARY_LIGHT ?= "#D6EAF8"
!$COLOR_PRIMARY_DARK ?= "#D6EAF8"

!$COLOR_WARNING ?= "#FCF3CF"
!$COLOR_WARNING_LIGHT ?= "#FCF3CF"
!$COLOR_WARNING_DARK ?= "#FCF3CF"

!$COLOR_SUCCESS ?= "#D5F5E3"
!$COLOR_SUCCESS_LIGHT ?= "#D5F5E3"
!$COLOR_SUCCESS_DARK ?= "#D5F5E3"

!$COLOR_ERROR ?= "#CD0000"
!$COLOR_ERROR_LIGHT ?= "#CD0000"
!$COLOR_ERROR_DARK ?= "#CD0000"

!$COLOR_BODY ?= "#ffffff"
!$BACKGROUND_COLOR ?= $COLOR_PRIMARY_LIGHT
!$COLOR_BORDER ?= "#5D6D7E"

!$COLOR_TEXT ?= "#000000"
!$COLOR_TEXT_LIGHT ?= $COLOR_BODY


' COLOR_LIGHT
' COLOR_DARK