
!$COLOR_FONT_COMPONENT ?= $COLOR_FONT
!$STYLE_FONT_COMPONENT ?= ""

!$COLOR_BACKGROUND_COMPONENT ?= $COLOR_PRIMARY
!$ALIGNMENT_HORIZONTAL_COMPONENT ?= "left"

!$MARGIN_COMPONENT ?= 20
!$PADDING_COMPONENT ?= 15
!$ROUND_CORNER_COMPONENT ?= $ROUND_CORNER

!$COLOR_LINE_COMPONENT ?= $COLOR_LINE
!$SIZE_LINE_COMPONENT ?= $SIZE_LINE