
!$FONT_COLOR_COMPONENT ?= $FONT_COLOR
!$FONT_STYLE_COMPONENT ?= ""

!$BACKGROUND_COLOR_COMPONENT ?= $COLOR_PRIMARY
!$HORIZONTAL_ALIGNMENT_COMPONENT ?= "left"

!$MARGIN_COMPONENT ?= 20
!$PADDING_COMPONENT ?= 15
!$ROUND_CORNER_COMPONENT ?= $ROUND_CORNER

!$LINE_COLOR_COMPONENT ?= $LINE_COLOR
!$LINE_SIZE_COMPONENT ?= $LINE_SIZE