
'---------------------------------------------------------
' Border Radius Utility Variables
'---------------------------------------------------------

!$ROUND_0 ?= 0
!$ROUND_1 ?= 5
!$ROUND_2 ?= 10
!$ROUND_3 ?= 15
!$ROUND_4 ?= 20
!$ROUND_5 ?= 30

!$ROUND_PILL ?= 50
!$ROUND_CIRCLE ?= 100

