
!$FONT_COLOR_ELEMENT ?= $FONT_COLOR
!$FONT_STYLE_ELEMENT ?= ""

!$BACKGROUND_COLOR_ELEMENT_COMPOSITE ?= "PRIMARY_LIGHT"
!$BACKGROUND_COLOR_ELEMENT ?= "PRIMARY"
!$HORIZONTAL_ALIGNMENT_ELEMENT ?= "left"

!$MARGIN_ELEMENT ?= 20
!$PADDING_ELEMENT ?= 15
!$ROUND_CORNER_ELEMENT ?= $ROUND_CORNER

!$LINE_COLOR_ELEMENT ?= $LINE_COLOR
!$LINE_SIZE_ELEMENT ?= $LINE_SIZE