
!$COLOR_FONT_ELEMENT ?= $COLOR_FONT
!$STYLE_FONT_ELEMENT ?= ""

!$COLOR_BACKGROUND_ELEMENT_COMPOSITE ?= "PRIMARY_LIGHT"
!$COLOR_BACKGROUND_ELEMENT ?= "PRIMARY"
!$ALIGNMENT_HORIZONTAL_ELEMENT ?= "left"

!$MARGIN_ELEMENT ?= 20
!$PADDING_ELEMENT ?= 15
!$ROUND_CORNER_ELEMENT ?= $ROUND_CORNER

!$COLOR_LINE_ELEMENT ?= $COLOR_LINE
!$SIZE_LINE_ELEMENT ?= $SIZE_LINE