
'---------------------------------------------------------
' Font Constants
'
' !$variable_name ?= "variable_value"
'---------------------------------------------------------

!$NAME_FONT ?= "Segoe UI"
!$SIZE_FONT ?= 12
!$SIZE_FONT_TITLE ?= 18
!$SIZE_FONT_LEGEND ?= 11
!$SIZE_FONT_ARROW ?= 11

!$COLOR_FONT ?= $COLOR_TEXT