'---------------------------------------------------------
' Height Utility Variables
'---------------------------------------------------------

!$HEIGHT_XS ?= 50
!$HEIGHT_SM ?= 75
!$HEIGHT_MD ?= 100
!$HEIGHT_LG ?= 150
!$HEIGHT_XL ?= 200
