
'---------------------------------------------------------
' Icon Constants
'
' !$variable_name ?= "variable_value"
'---------------------------------------------------------


'Actors
!$STYLE_ACTOR ?= awesome

!$COLOR_BORDER_ACTOR ?= "#0D47A1"
!$SIZE_BORDER_ACTOR ?= 3
!$COLOR_BACKGROUND_ACTOR ?= "#90CAF9"

