'---------------------------------------------------------
' Width Utility Variables
'---------------------------------------------------------

!$WIDTH_XS ?= 75
!$WIDTH_SM ?= 150
!$WIDTH_MD ?= 250
!$WIDTH_LG ?= 350
!$WIDTH_XL ?= 500
!$WIDTH_XXL ?= 700

