
!if ($TOGAF_THEME_ENABLED)

'This is the surface colour

!$COLOR_MOTIVATION_LIGHT ?= $TOGAF_COLOR_MOTIVATION
!$COLOR_MOTIVATION_DARK ?= $TOGAF_COLOR_MOTIVATION

!$COLOR_STRATEGY_LIGHT ?= $TOGAF_COLOR_STRATEGY
!$COLOR_STRATEGY_DARK ?= $TOGAF_COLOR_STRATEGY

!$COLOR_BUSINESS_LIGHT ?= $TOGAF_COLOR_BUSINESS
!$COLOR_BUSINESS_DARK ?= $TOGAF_COLOR_BUSINESS

!$COLOR_APPLICATION_LIGHT ?= $TOGAF_COLOR_APPLICATION
!$COLOR_APPLICATION_DARK ?= $TOGAF_COLOR_APPLICATION

!$COLOR_TECHNOLOGY_LIGHT ?= $TOGAF_COLOR_TECHNOLOGY
!$COLOR_TECHNOLOGY_DARK ?= $TOGAF_COLOR_TECHNOLOGY

!$COLOR_IMPLEMENTATION_LIGHT ?= $TOGAF_COLOR_IMPLEMENTATION
!$COLOR_IMPLEMENTATION_DARK ?= $TOGAF_COLOR_IMPLEMENTATION

!$COLOR_HIGHLIGHTED_LIGHT ?= $TOGAF_COLOR_HIGHLIGHTED
!$COLOR_HIGHLIGHTED_DARK ?= $TOGAF_COLOR_HIGHLIGHTED

!$COLOR_NEW_LIGHT ?= $TOGAF_COLOR_NEW
!$COLOR_NEW_DARK ?= $TOGAF_COLOR_NEW


!endif