
!if ($TOGAF_THEME_ENABLED)

'This is the surface colour

!$COLOR_MOTIVATION_LIGHT ?= $COLOR_TOGAF_MOTIVATION
!$COLOR_MOTIVATION_DARK ?= $COLOR_TOGAF_MOTIVATION

!$COLOR_STRATEGY_LIGHT ?= $COLOR_TOGAF_STRATEGY
!$COLOR_STRATEGY_DARK ?= $COLOR_TOGAF_STRATEGY

!$COLOR_BUSINESS_LIGHT ?= $COLOR_TOGAF_BUSINESS
!$COLOR_BUSINESS_DARK ?= $COLOR_TOGAF_BUSINESS

!$COLOR_APPLICATION_LIGHT ?= $COLOR_TOGAF_APPLICATION
!$COLOR_APPLICATION_DARK ?= $COLOR_TOGAF_APPLICATION

!$COLOR_TECHNOLOGY_LIGHT ?= $COLOR_TOGAF_TECHNOLOGY
!$COLOR_TECHNOLOGY_DARK ?= $COLOR_TOGAF_TECHNOLOGY

!$COLOR_IMPLEMENTATION_LIGHT ?= $COLOR_TOGAF_IMPLEMENTATION
!$COLOR_IMPLEMENTATION_DARK ?= $COLOR_TOGAF_IMPLEMENTATION

!$COLOR_HIGHLIGHTED_LIGHT ?= $COLOR_TOGAF_HIGHLIGHTED
!$COLOR_HIGHLIGHTED_DARK ?= $COLOR_TOGAF_HIGHLIGHTED

!$COLOR_NEW_LIGHT ?= $COLOR_TOGAF_NEW
!$COLOR_NEW_DARK ?= $COLOR_TOGAF_NEW


!endif