
!function $get_text_color($bg_var_name, $dark_text_var_name="COLOR_TEXT", $light_text_var_name="COLOR_TEXT_LIGHT")
  

  ' Strip the '$' character if it was passed inside the string parameter
  !$bg = %substr($bg_var_name, 0, 1) == "$" ? %substr($bg_var_name, 1) : $bg_var_name
  !$dark = %substr($dark_text_var_name, 0, 1) == "$" ? %substr($dark_text_var_name, 1) : $dark_text_var_name
  !$light = %substr($light_text_var_name, 0, 1) == "$" ? %substr($light_text_var_name, 1) : $light_text_var_name

  ' Look up the actual hex values using the string names
  !$bg_val = $resolve_variable($bg)
  !$dark_val = $resolve_variable($dark)
  !$light_val = $resolve_variable($light)

  ' Construct and return the standard PlantUML selective contrast token
  !return "#?" + $bg_val + "?" + $dark_val + ":" + $light_val
!endfunction

'
' Normalizes a color variable reference:
'   COLOR_PRIMARY     -> PRIMARY
'   $COLOR_PRIMARY    -> PRIMARY
'   $PRIMARY          -> PRIMARY
'   PRIMARY           -> PRIMARY
'
!function $normalize_color_name($name)
  !$clean = $strip_dollar($name)
  !if %substr($clean, 0, 6) == "COLOR_"
    !return %substr($clean, 6)
  !endif
  !return $clean
!endfunction


!function $semantic_color_variable($name)
  !return "COLOR_" + $normalize_color_name($name)
!endfunction


!function $get_semantic_text_color( $semantic_suffix, $dark_text_var_name="COLOR_TEXT", $light_text_var_name="COLOR_TEXT_LIGHT")
  
  ' Call the base contrast function using the constructed variable name
  !return $get_text_color(
    $semantic_color_variable( $semantic_suffix ),
    $dark_text_var_name,
    $light_text_var_name
  )

!endfunction



!function $get_color($var_name)
  !$col = $strip_dollar($var_name)
  !$col_val = %get_variable_value($col)
  !return "#?" + $col_val

!endfunction


!function $get_semantic_color($semantic_suffix)
  ' Call the base contrast function using the constructed variable name
  !return $get_color( $semantic_color_variable( $semantic_suffix ) )
!endfunction

