!function $first_context_color($context0="", $context1="", $context2="", $context3="", $context4="")

  !if ($context0 != "") && ($is_special_style_token($context0) == %false())
      !return $context0
  !endif

  !if ($context1 != "") && ($is_special_style_token($context1) == %false())
      !return $context1
  !endif

  !if ($context2 != "") && ($is_special_style_token($context2) == %false())
      !return $context2
  !endif

  !if ($context3 != "") && ($is_special_style_token($context3) == %false())
      !return $context3
  !endif

  !if ($context4 != "") && ($is_special_style_token($context4) == %false())
      !return $context4
  !endif

  !return ""

!endfunction



!function $resolve_style_color($tokenOrColor, $context0="", $context1="", $context2="", $context3="", $context4="" )
  '!$tokenOrColorIsSpecial = $is_special_style_token($tokenOrColor)
  !$contextColor = $first_context_color($context0, $context1, $context2, $context3, $context4)

  '
  ' Validation
  '
  !if ($tokenOrColor == "") && ($contextColor == "")
      !assert 0 == 1 : "MB_UML :: BLANK.BLANK[" + $tokenOrColor + "] (resolve_style_color) requires a tokenOrColor or context color"
  !endif

  '
  ' AUTO
  '
  !if ($tokenOrColor == "AUTO")

      !if ($contextColor == "")
          !assert 0 == 1 : "MB_UML :: AUTO (resolve_style_color) requires a context color"
      !endif

      !return $get_semantic_text_color($contextColor)

  '
  ' CURRENT
  '
  !elseif ($tokenOrColor == "CURRENT")

      !if ($contextColor == "")
          !assert 0 == 1 : "MB_UML :: CURRENT (resolve_style_color) requires a context color"
      !endif

      !return $resolve_style_color($contextColor)

  '
  ' DARKEN
  '
  !elseif (%strpos($tokenOrColor, "DARKEN") == 0)

      !if ($contextColor == "")
          !assert 0 == 1 : "MB_UML :: " + $tokenOrColor + " (resolve_style_color) requires a context color"
      !endif

      !return $darken_color( $contextColor, $tokenOrColor )

  '
  ' LIGHTEN
  '
  !elseif (%strpos($tokenOrColor, "LIGHTEN") == 0)

      !if ($contextColor == "")
          !assert 0 == 1 : "MB_UML :: " + $tokenOrColor + " (resolve_style_color) requires a context color"
      !endif

      !return $lighten_color($contextColor, $tokenOrColor )

  '
  ' Literal color
  '
  !elseif ($is_literal_color($tokenOrColor))
      !return $tokenOrColor
  '
  ' Semantic text token
  '
  !elseif ($ends_with_text($tokenOrColor) == %true())
      !$base = %substr($tokenOrColor, 0,%strlen($tokenOrColor) - 5 )
      !return $get_semantic_text_color($base)
  '
  ' Semantic color token
  '
  !else
      !return $get_semantic_color($tokenOrColor)
  !endif

!endfunction
 

 !function $resolve_literal_color($tokenOrColor)
  !$color = $resolve_style_color($tokenOrColor)

  $assert_literal_color($color)
  !return %upper($color)
!endfunction
