

!function $strip_prefix($value, $prefix)

    !$prefixWithSeparator = $prefix + "_"

    !if %strpos($value, $prefixWithSeparator) == 0
        !return %substr(
            $value,
            %strlen($prefixWithSeparator)
        )
    !endif

    !return $value

!endfunction


!function $ends_with($value, $suffix)

  !$suffix_len = %strlen($suffix)
  !$value_len = %strlen($value)

  !if $value_len < $suffix_len
    !return %false()
  !endif

  !return %substr($value, $value_len - $suffix_len, $suffix_len) == $suffix

!endfunction

!function $ends_with_text($value)
  !return $ends_with($value, "_TEXT")

!endfunction


!function $is_special_style_token($token)
  !$tokenU = %upper($token)

  'token value should not be coming in with a prefix, like being processed by get_semantic_color
  !if $tokenU == "AUTO" 
    !return %true()
  !elseif $tokenU == "CURRENT"
    !return %true()
  !elseif %strpos($tokenU,"DARKEN") == 0
    !return %true()
  !elseif %strpos($tokenU,"LIGHTEN") == 0
    !return %true()
  !endif

  !return %false()

!endfunction



!procedure $build_array($arrayVarName, $value0=$UNSET, $value1=$UNSET, $value2=$UNSET, $value3=$UNSET, $value4=$UNSET, $value5=$UNSET, $value6=$UNSET, $value7=$UNSET, $value8=$UNSET, $value9=$UNSET)

  %set_variable_value($arrayVarName, []) 
  !$result = %get_variable_value($arrayVarName)

  %set_variable_value($arrayVarName, $result)

  !$index = 0

  !if ($value0 != $UNSET) && ($value0 != "")
      !$result[$index] = $value0
      !$index = $index + 1
  !endif

  !if ($value1 != $UNSET) && ($value1 != "")
      !$result[$index] = $value1
      !$index = $index + 1
  !endif

  !if ($value2 != $UNSET) && ($value2 != "")
      !$result[$index] = $value2
      !$index = $index + 1
  !endif

  !if ($value3 != $UNSET) && ($value3 != "")
      !$result[$index] = $value3
      !$index = $index + 1
  !endif

  !if ($value4 != $UNSET) && ($value4 != "")
      !$result[$index] = $value4
      !$index = $index + 1
  !endif

  !if ($value5 != $UNSET) && ($value5 != "")
      !$result[$index] = $value5
      !$index = $index + 1
  !endif

  !if ($value6 != $UNSET) && ($value6 != "")
      !$result[$index] = $value6
      !$index = $index + 1
  !endif

  !if ($value7 != $UNSET) && ($value7 != "")
      !$result[$index] = $value7
      !$index = $index + 1
  !endif

  !if ($value8 != $UNSET) && ($value8 != "")
      !$result[$index] = $value8
      !$index = $index + 1
  !endif

  !if ($value9 != $UNSET) && ($value9 != "")
      !$result[$index] = $value9
      !$index = $index + 1
  !endif



!endfunction

