
'---------------------------------------------------------
' Component Styles
'---------------------------------------------------------

!procedure Write_Lib_Style_Stdlib_Component()


!endprocedure