
'---------------------------------------------------------
' Element Styles
'---------------------------------------------------------

!procedure Write_Lib_Style_Stdlib_Element()

    !$cBackgroundColor = $resolve_style_color($COLOR_BACKGROUND_ELEMENT)
    !$cFontColor = $resolve_style_color($COLOR_FONT_ELEMENT, $cBackgroundColor, $COLOR_BACKGROUND_ELEMENT, $COLOR_BACKGROUND, $COLOR_BODY )

    'COLOR_BACKGROUND_ELEMENT_COMPOSITE
    !$ccBackgroundColor = $resolve_style_color("DARKEN", $cBackgroundColor)
    !$ccFontColor = $resolve_style_color("AUTO", $ccBackgroundColor)

<style>

element {
    BackgroundColor $cBackgroundColor
    LineColor $ccFontColor
    FontColor $cFontColor

    LineThickness $SIZE_LINE_ELEMENT
    RoundCorner $ROUND_CORNER_ELEMENT
    Margin $MARGIN_ELEMENT
    Padding $PADDING_ELEMENT

}

component {

}

.composite-container {
    BackgroundColor $ccBackgroundColor
    LineColor $ccBackgroundColor
    FontColor $ccFontColor
}

</style>

!endprocedure