'---------------------------------------------------------
' Title Styles
'---------------------------------------------------------

!procedure Write_Lib_Style_Stdlib_Title()

!$tBackgroundColor = $resolve_style_color($COLOR_BACKGROUND_TITLE)
!$tFontColor = $resolve_style_color($COLOR_FONT_TITLE, $COLOR_BACKGROUND_TITLE, $COLOR_BACKGROUND, $COLOR_BODY )

<style>
title {
    BackgroundColor $tBackgroundColor
    HorizontalAlignment $ALIGNMENT_HORIZONTAL_TITLE
    FontSize $SIZE_FONT_TITLE
    FontColor $tFontColor
    FontStyle $STYLE_FONT_TITLE
    LineColor $tBackgroundColor


    LineThickness $SIZE_LINE_TITLE
    RoundCorner $ROUND_CORNER_TITLE
    Margin $MARGIN_TITLE
    Padding $PADDING_TITLE
}
</style>

!endprocedure

'---------------------------------------------------------
' Title Element
'---------------------------------------------------------
