
!if ($OH_THEME_ENABLED)

'Set OH Colours

!$COLOR_PRIMARY = $OH_COLOR_PRIMARY
!$COLOR_PRIMARY_LIGHT = $OH_COLOR_PRIMARY_LIGHT
!$COLOR_PRIMARY_DARK = $OH_COLOR_PRIMARY_DARK

!$COLOR_WARNING = $OH_COLOR_WARNING
!$COLOR_WARNING_LIGHT = $OH_COLOR_WARNING_LIGHT
!$COLOR_WARNING_DARK = $OH_COLOR_WARNING_DARK

!$COLOR_SUCCESS = $OH_COLOR_SUCCESS
!$COLOR_SUCCESS_LIGHT = $OH_COLOR_SUCCESS_LIGHT
!$COLOR_SUCCESS_DARK = $OH_COLOR_SUCCESS_DARK

!$COLOR_ERROR = $OH_COLOR_ERROR
!$COLOR_ERROR_LIGHT = $OH_COLOR_ERROR_LIGHT
!$COLOR_ERROR_DARK = $OH_COLOR_ERROR_DARK

!$COLOR_TEXT = $OH_COLOR_TEXT
!$COLOR_BORDER ?= $OH_COLOR_BORDER


'If there are a lot of variables, this could be moved into a separate _togaf.puml file

!if ($TOGAF_THEME_ENABLED)

    'Set OH Colours to TOGAF
    !$TOGAF_COLOR_BUSINESS ?= $OH_COLOR_WARNING
    !$TOGAF_COLOR_LOGICAL ?= $OH_COLOR_PRIMARY
    !$TOGAF_COLOR_DEPLOYMENT ?= "#FAD7A0"
    !$TOGAF_COLOR_TECHNOLOGY ?= $OH_COLOR_SUCCESS
    !$TOGAF_COLOR_EXTERNAL ?= "#E8DAEF"

!endif 'TOGAF_THEME_ENABLED

!endif