
!if ($OH_THEME_ENABLED)

'Set OH Colours

!$COLOR_PRIMARY = $COLOR_OH_PRIMARY
!$COLOR_PRIMARY_LIGHT = $COLOR_OH_PRIMARY_LIGHT
!$COLOR_PRIMARY_DARK = $COLOR_OH_PRIMARY_DARK

!$COLOR_WARNING = $COLOR_OH_WARNING
!$COLOR_WARNING_LIGHT = $COLOR_OH_WARNING_LIGHT
!$COLOR_WARNING_DARK = $COLOR_OH_WARNING_DARK

!$COLOR_SUCCESS = $COLOR_OH_SUCCESS
!$COLOR_SUCCESS_LIGHT = $COLOR_OH_SUCCESS_LIGHT
!$COLOR_SUCCESS_DARK = $COLOR_OH_SUCCESS_DARK

!$COLOR_ERROR = $COLOR_OH_ERROR
!$COLOR_ERROR_LIGHT = $COLOR_OH_ERROR_LIGHT
!$COLOR_ERROR_DARK = $COLOR_OH_ERROR_DARK

!$COLOR_TEXT = $COLOR_OH_TEXT
!$COLOR_BORDER ?= $COLOR_OH_BORDER


'If there are a lot of variables, this could be moved into a separate _togaf.puml file


!if ($TOGAF_THEME_ENABLED)

    'This is the surface colour

    !$COLOR_MOTIVATION_LIGHT ?= $COLOR_OH_MOTIVATION_LIGHT
    !$COLOR_MOTIVATION_DARK ?= $COLOR_OH_MOTIVATION_DARK

    !$COLOR_STRATEGY_LIGHT ?= $COLOR_OH_STRATEGY_LIGHT
    !$COLOR_STRATEGY_DARK ?= $COLOR_OH_STRATEGY_DARK

    !$COLOR_BUSINESS_LIGHT ?= $COLOR_OH_BUSINESS_LIGHT
    !$COLOR_BUSINESS_DARK ?= $COLOR_OH_BUSINESS_DARK

    !$COLOR_APPLICATION_LIGHT ?= $COLOR_OH_APPLICATION_LIGHT
    !$COLOR_APPLICATION_DARK ?= $COLOR_OH_APPLICATION_DARK

    !$COLOR_TECHNOLOGY_LIGHT ?= $COLOR_OH_TECHNOLOGY_LIGHT
    !$COLOR_TECHNOLOGY_DARK ?= $COLOR_OH_TECHNOLOGY_DARK

    !$COLOR_IMPLEMENTATION_LIGHT ?= $COLOR_OH_IMPLEMENTATION_LIGHT
    !$COLOR_IMPLEMENTATION_DARK ?= $COLOR_OH_IMPLEMENTATION_DARK

    !$COLOR_HIGHLIGHTED_LIGHT ?= $COLOR_OH_HIGHLIGHTED_LIGHT
    !$COLOR_HIGHLIGHTED_DARK ?= $COLOR_OH_HIGHLIGHTED_DARK

    !$COLOR_NEW_LIGHT ?= $COLOR_OH_NEW_LIGHT
    !$COLOR_NEW_DARK ?= $COLOR_OH_NEW_DARK


!endif

!endif

