
!if ($OH_THEME_ENABLED)

'Set OH Colours

!$COLOR_PRIMARY = $OH_COLOR_PRIMARY
!$COLOR_PRIMARY_LIGHT = $OH_COLOR_PRIMARY_LIGHT
!$COLOR_PRIMARY_DARK = $OH_COLOR_PRIMARY_DARK

!$COLOR_WARNING = $OH_COLOR_WARNING
!$COLOR_WARNING_LIGHT = $OH_COLOR_WARNING_LIGHT
!$COLOR_WARNING_DARK = $OH_COLOR_WARNING_DARK

!$COLOR_SUCCESS = $OH_COLOR_SUCCESS
!$COLOR_SUCCESS_LIGHT = $OH_COLOR_SUCCESS_LIGHT
!$COLOR_SUCCESS_DARK = $OH_COLOR_SUCCESS_DARK

!$COLOR_ERROR = $OH_COLOR_ERROR
!$COLOR_ERROR_LIGHT = $OH_COLOR_ERROR_LIGHT
!$COLOR_ERROR_DARK = $OH_COLOR_ERROR_DARK

!$COLOR_TEXT = $OH_COLOR_TEXT
!$COLOR_BORDER ?= $OH_COLOR_BORDER


'If there are a lot of variables, this could be moved into a separate _togaf.puml file


!if ($TOGAF_THEME_ENABLED)

    'This is the surface colour

    !$COLOR_MOTIVATION_LIGHT ?= $OH_COLOR_MOTIVATION_LIGHT
    !$COLOR_MOTIVATION_DARK ?= $OH_COLOR_MOTIVATION_DARK

    !$COLOR_STRATEGY_LIGHT ?= $OH_COLOR_STRATEGY_LIGHT
    !$COLOR_STRATEGY_DARK ?= $OH_COLOR_STRATEGY_DARK

    !$COLOR_BUSINESS_LIGHT ?= $OH_COLOR_BUSINESS_LIGHT
    !$COLOR_BUSINESS_DARK ?= $OH_COLOR_BUSINESS_DARK

    !$COLOR_APPLICATION_LIGHT ?= $OH_COLOR_APPLICATION_LIGHT
    !$COLOR_APPLICATION_DARK ?= $OH_COLOR_APPLICATION_DARK

    !$COLOR_TECHNOLOGY_LIGHT ?= $OH_COLOR_TECHNOLOGY_LIGHT
    !$COLOR_TECHNOLOGY_DARK ?= $OH_COLOR_TECHNOLOGY_DARK

    !$COLOR_IMPLEMENTATION_LIGHT ?= $OH_COLOR_IMPLEMENTATION_LIGHT
    !$COLOR_IMPLEMENTATION_DARK ?= $OH_COLOR_IMPLEMENTATION_DARK

    !$COLOR_HIGHLIGHTED_LIGHT ?= $OH_COLOR_HIGHLIGHTED_LIGHT
    !$COLOR_HIGHLIGHTED_DARK ?= $OH_COLOR_HIGHLIGHTED_DARK

    !$COLOR_NEW_LIGHT ?= $OH_COLOR_NEW_LIGHT
    !$COLOR_NEW_DARK ?= $OH_COLOR_NEW_DARK


!endif

!endif

