

!include _title.puml

!procedure Preload_Lib_Styles_OntarioHealth()
    !if ($OH_THEME_ENABLED)
        
    !endif
!endprocedure

!procedure Load_Lib_Styles_OntarioHealth()

    !if ($OH_THEME_ENABLED)
        Write_Lib_Style_OntarioHealth_Title()
    !endif
!endprocedure 