

' $get_semantic_text_color("PRIMARY_DARK")

!$BACKGROUND_COLOR_TITLE = $get_semantic_color("PRIMARY_DARK")
!$FONT_COLOR_TITLE = $get_text_color($BACKGROUND_COLOR_TITLE)
    
!$LINE_COLOR_TITLE = $BACKGROUND_COLOR_TITLE
